name: generate animation

on:
  # ejecutar automáticamente cada día
  schedule:
    - cron: "0 0 * * *"

  # permite ejecutarlo manualmente
  workflow_dispatch:

  # ejecutar en cada push a main
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:

      # Generar la animación snake desde el gráfico de contribuciones
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}

          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-light
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Publicar los SVG en la rama output
      - name: push snake animation to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
